name: flutter_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^4.0.6
  json_annotation: ^4.7.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true

